[2022-02-28 19:30:31,705] INFO [GroupCoordinator 2]: Member console-consumer-039088b7-4622-4e52-9862-e7ba6f73ecde in group console-consumer-69689 has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2022-02-28 19:30:33,430] WARN Client session timed out, have not heard from server in 4189710ms for session id 0x200b5f9003c0008 (org.apache.zookeeper.ClientCnxn)
[2022-02-28 19:30:34,243] INFO [GroupCoordinator 2]: Preparing to rebalance group console-consumer-69689 in state PreparingRebalance with old generation 3 (__consumer_offsets-9) (reason: removing member console-consumer-039088b7-4622-4e52-9862-e7ba6f73ecde on heartbeat expiration) (kafka.coordinator.group.GroupCoordinator)
[2022-02-28 19:30:34,362] WARN Session 0x200b5f9003c0008 for sever localhost/127.0.0.1:2182, Closing socket connection. Attempting reconnect except it is a SessionExpiredException. (org.apache.zookeeper.ClientCnxn)
org.apache.zookeeper.ClientCnxn$SessionTimeoutException: Client session timed out, have not heard from server in 4189710ms for session id 0x200b5f9003c0008
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1258)
[2022-02-28 19:30:34,503] INFO [GroupCoordinator 2]: Group console-consumer-69689 with generation 4 is now empty (__consumer_offsets-9) (kafka.coordinator.group.GroupCoordinator)
[2022-02-28 19:30:36,765] INFO Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2181. (org.apache.zookeeper.ClientCnxn)
[2022-02-28 19:30:36,782] INFO SASL config status: Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2022-02-28 19:30:36,894] INFO Socket connection established, initiating session, client: /0:0:0:0:0:0:0:1:54342, server: localhost/0:0:0:0:0:0:0:1:2181 (org.apache.zookeeper.ClientCnxn)
[2022-02-28 19:30:37,270] WARN Unable to reconnect to ZooKeeper service, session 0x200b5f9003c0008 has expired (org.apache.zookeeper.ClientCnxn)
[2022-02-28 19:30:37,285] WARN Session 0x200b5f9003c0008 for sever localhost/0:0:0:0:0:0:0:1:2181, Closing socket connection. Attempting reconnect except it is a SessionExpiredException. (org.apache.zookeeper.ClientCnxn)
org.apache.zookeeper.ClientCnxn$SessionExpiredException: Unable to reconnect to ZooKeeper service, session 0x200b5f9003c0008 has expired
	at org.apache.zookeeper.ClientCnxn$SendThread.onConnected(ClientCnxn.java:1434)
	at org.apache.zookeeper.ClientCnxnSocket.readConnectResult(ClientCnxnSocket.java:154)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doIO(ClientCnxnSocketNIO.java:86)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:350)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1290)
[2022-02-28 19:30:37,381] INFO [ZooKeeperClient Kafka server] Session expired. (kafka.zookeeper.ZooKeeperClient)
[2022-02-28 19:30:37,352] INFO EventThread shut down for session: 0x200b5f9003c0008 (org.apache.zookeeper.ClientCnxn)
[2022-02-28 19:30:37,414] INFO [GroupCoordinator 2]: Dynamic member with unknown member id joins group console-consumer-69689 in Empty state. Created a new member id console-consumer-0e81e736-c7cb-4619-94d1-df7cdafc6b03 and request the member to rejoin with this id. (kafka.coordinator.group.GroupCoordinator)
[2022-02-28 19:30:37,549] INFO [ZooKeeperClient Kafka server] Initializing a new session to localhost:2181,localhost:2182,localhost:2183. (kafka.zookeeper.ZooKeeperClient)
[2022-02-28 19:30:37,590] INFO Initiating client connection, connectString=localhost:2181,localhost:2182,localhost:2183 sessionTimeout=18000 watcher=kafka.zookeeper.ZooKeeperClient$ZooKeeperClientWatcher$@7c7b252e (org.apache.zookeeper.ZooKeeper)
[2022-02-28 19:30:37,607] INFO [GroupCoordinator 2]: Preparing to rebalance group console-consumer-69689 in state PreparingRebalance with old generation 4 (__consumer_offsets-9) (reason: Adding new member console-consumer-0e81e736-c7cb-4619-94d1-df7cdafc6b03 with group instance id None) (kafka.coordinator.group.GroupCoordinator)
[2022-02-28 19:30:37,705] INFO [GroupCoordinator 2]: Stabilized group console-consumer-69689 generation 5 (__consumer_offsets-9) with 1 members (kafka.coordinator.group.GroupCoordinator)
[2022-02-28 19:30:37,728] INFO jute.maxbuffer value is 4194304 Bytes (org.apache.zookeeper.ClientCnxnSocket)
[2022-02-28 19:30:37,812] INFO zookeeper.request.timeout value is 0. feature enabled=false (org.apache.zookeeper.ClientCnxn)
[2022-02-28 19:30:37,876] INFO [GroupCoordinator 2]: Assignment received from leader console-consumer-0e81e736-c7cb-4619-94d1-df7cdafc6b03 for group console-consumer-69689 for generation 5. The group has 1 members, 0 of which are static. (kafka.coordinator.group.GroupCoordinator)
[2022-02-28 19:30:37,916] INFO Opening socket connection to server localhost/127.0.0.1:2183. (org.apache.zookeeper.ClientCnxn)
[2022-02-28 19:30:37,916] INFO SASL config status: Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2022-02-28 19:30:37,928] INFO Socket connection established, initiating session, client: /127.0.0.1:54346, server: localhost/127.0.0.1:2183 (org.apache.zookeeper.ClientCnxn)
[2022-02-28 19:30:39,639] INFO Session establishment complete on server localhost/127.0.0.1:2183, session id = 0x300b5f942b40009, negotiated timeout = 18000 (org.apache.zookeeper.ClientCnxn)
[2022-02-28 19:30:40,396] INFO Updated cache from existing FinalizedFeaturesAndEpoch(features=Features{}, epoch=0) to latest FinalizedFeaturesAndEpoch(features=Features{}, epoch=0). (kafka.server.FinalizedFeatureCache)
[2022-02-28 19:30:40,398] INFO Creating /brokers/ids/2 (is it secure? false) (kafka.zk.KafkaZkClient)
[2022-02-28 19:30:40,963] INFO Stat of the created znode at /brokers/ids/2 is: 4294967735,4294967735,1646056840699,1646056840699,1,0,0,216372864284360713,202,0,4294967735
 (kafka.zk.KafkaZkClient)
[2022-02-28 19:30:41,065] INFO Registered broker 2 at path /brokers/ids/2 with addresses: PLAINTEXT://localhost:9093, czxid (broker epoch): 4294967735 (kafka.zk.KafkaZkClient)
[2022-02-28 19:30:41,759] INFO [ReplicaFetcher replicaId=2, leaderId=1, fetcherId=0] Partition topic02-2 has an older epoch (5) than the current leader. Will await the new LeaderAndIsr state before resuming fetching. (kafka.server.ReplicaFetcherThread)
[2022-02-28 19:30:41,876] WARN [ReplicaFetcher replicaId=2, leaderId=1, fetcherId=0] Partition topic02-2 marked as failed (kafka.server.ReplicaFetcherThread)
[2022-02-28 19:30:41,930] INFO [ReplicaFetcher replicaId=2, leaderId=1, fetcherId=0] Partition topic02-1 has an older epoch (4) than the current leader. Will await the new LeaderAndIsr state before resuming fetching. (kafka.server.ReplicaFetcherThread)
[2022-02-28 19:30:41,963] WARN [ReplicaFetcher replicaId=2, leaderId=1, fetcherId=0] Partition topic02-1 marked as failed (kafka.server.ReplicaFetcherThread)
[2022-02-28 19:30:41,983] INFO [ReplicaFetcher replicaId=2, leaderId=1, fetcherId=0] Partition topic02-0 has an older epoch (5) than the current leader. Will await the new LeaderAndIsr state before resuming fetching. (kafka.server.ReplicaFetcherThread)
[2022-02-28 19:30:41,990] WARN [ReplicaFetcher replicaId=2, leaderId=1, fetcherId=0] Partition topic02-0 marked as failed (kafka.server.ReplicaFetcherThread)
[2022-02-28 19:30:42,089] INFO [ReplicaFetcherManager on broker 2] Removed fetcher for partitions HashSet(topic02-2, topic02-1, topic02-0) (kafka.server.ReplicaFetcherManager)
[2022-02-28 19:30:42,148] INFO [ReplicaFetcherManager on broker 2] Added fetcher to broker 1 for partitions Map(topic02-0 -> InitialFetchState(Some(nwnpDpO3R5CsaOttfczqkA),BrokerEndPoint(id=1, host=localhost:9092),7,754496), topic02-2 -> InitialFetchState(Some(nwnpDpO3R5CsaOttfczqkA),BrokerEndPoint(id=1, host=localhost:9092),7,508515), topic02-1 -> InitialFetchState(Some(nwnpDpO3R5CsaOttfczqkA),BrokerEndPoint(id=1, host=localhost:9092),6,737273)) (kafka.server.ReplicaFetcherManager)
[2022-02-28 19:30:42,174] INFO [ReplicaFetcherManager on broker 2] Removed fetcher for partitions HashSet(__consumer_offsets-30, __consumer_offsets-21, __consumer_offsets-33, __consumer_offsets-36, __consumer_offsets-48, __consumer_offsets-6, __consumer_offsets-0, __consumer_offsets-45, __consumer_offsets-27, __consumer_offsets-9, __consumer_offsets-42, __consumer_offsets-3, __consumer_offsets-18, __consumer_offsets-15, __consumer_offsets-24, __consumer_offsets-39, __consumer_offsets-12) (kafka.server.ReplicaFetcherManager)
[2022-02-28 19:59:42,342] WARN Session 0x300b5f942b40009 for sever localhost/127.0.0.1:2183, Closing socket connection. Attempting reconnect except it is a SessionExpiredException. (org.apache.zookeeper.ClientCnxn)
java.io.IOException: An existing connection was forcibly closed by the remote host
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doIO(ClientCnxnSocketNIO.java:74)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:350)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1290)
[2022-02-28 19:59:43,497] INFO [ReplicaFetcher replicaId=2, leaderId=1, fetcherId=0] Node 1 disconnected. (org.apache.kafka.clients.NetworkClient)
[2022-02-28 19:59:43,503] INFO [ReplicaFetcher replicaId=2, leaderId=1, fetcherId=0] Cancelled in-flight FETCH request with correlation id 141583 due to node 1 being disconnected (elapsed time since creation: 1727ms, elapsed time since send: 1727ms, request timeout: 30000ms) (org.apache.kafka.clients.NetworkClient)
[2022-02-28 19:59:43,516] INFO [ReplicaFetcher replicaId=2, leaderId=1, fetcherId=0] Client requested connection close from node 1 (org.apache.kafka.clients.NetworkClient)
[2022-02-28 19:59:43,516] INFO [ReplicaFetcher replicaId=2, leaderId=1, fetcherId=0] Error sending fetch request (sessionId=1143473828, epoch=3424) to node 1: (org.apache.kafka.clients.FetchSessionHandler)
java.io.IOException: Connection to 1 was disconnected before the response was read
	at org.apache.kafka.clients.NetworkClientUtils.sendAndReceive(NetworkClientUtils.java:99)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:109)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:219)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:322)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:137)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:136)
	at scala.Option.foreach(Option.scala:437)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:136)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:119)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2022-02-28 19:59:43,523] WARN [ReplicaFetcher replicaId=2, leaderId=1, fetcherId=0] Error in response for fetch request (type=FetchRequest, replicaId=2, maxWait=500, minBytes=1, maxBytes=10485760, fetchData={}, isolationLevel=READ_UNCOMMITTED, removed=, replaced=, metadata=(sessionId=1143473828, epoch=3424), rackId=) (kafka.server.ReplicaFetcherThread)
java.io.IOException: Connection to 1 was disconnected before the response was read
	at org.apache.kafka.clients.NetworkClientUtils.sendAndReceive(NetworkClientUtils.java:99)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:109)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:219)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:322)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:137)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:136)
	at scala.Option.foreach(Option.scala:437)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:136)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:119)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2022-02-28 19:59:44,426] INFO Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2182. (org.apache.zookeeper.ClientCnxn)
[2022-02-28 19:59:44,427] INFO SASL config status: Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2022-02-28 19:59:46,454] WARN Session 0x300b5f942b40009 for sever localhost/0:0:0:0:0:0:0:1:2182, Closing socket connection. Attempting reconnect except it is a SessionExpiredException. (org.apache.zookeeper.ClientCnxn)
java.net.ConnectException: Connection refused: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:344)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1290)
[2022-02-28 19:59:46,579] INFO [ReplicaFetcher replicaId=2, leaderId=1, fetcherId=0] Node 1 disconnected. (org.apache.kafka.clients.NetworkClient)
[2022-02-28 19:59:46,579] WARN [ReplicaFetcher replicaId=2, leaderId=1, fetcherId=0] Connection to node 1 (localhost/127.0.0.1:9092) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)
[2022-02-28 19:59:46,579] INFO [ReplicaFetcher replicaId=2, leaderId=1, fetcherId=0] Client requested connection close from node 1 (org.apache.kafka.clients.NetworkClient)
[2022-02-28 19:59:46,579] INFO [ReplicaFetcher replicaId=2, leaderId=1, fetcherId=0] Error sending fetch request (sessionId=1143473828, epoch=INITIAL) to node 1: (org.apache.kafka.clients.FetchSessionHandler)
java.io.IOException: Connection to localhost:9092 (id: 1 rack: null) failed.
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:70)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:104)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:219)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:322)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:137)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:136)
	at scala.Option.foreach(Option.scala:437)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:136)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:119)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2022-02-28 19:59:46,579] WARN [ReplicaFetcher replicaId=2, leaderId=1, fetcherId=0] Error in response for fetch request (type=FetchRequest, replicaId=2, maxWait=500, minBytes=1, maxBytes=10485760, fetchData={topic02-2=PartitionData(topicId=nwnpDpO3R5CsaOttfczqkA, fetchOffset=508515, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[7], lastFetchedEpoch=Optional[4]), topic02-1=PartitionData(topicId=nwnpDpO3R5CsaOttfczqkA, fetchOffset=737273, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[6], lastFetchedEpoch=Optional[4]), topic02-0=PartitionData(topicId=nwnpDpO3R5CsaOttfczqkA, fetchOffset=754496, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[7], lastFetchedEpoch=Optional[5])}, isolationLevel=READ_UNCOMMITTED, removed=, replaced=, metadata=(sessionId=1143473828, epoch=INITIAL), rackId=) (kafka.server.ReplicaFetcherThread)
java.io.IOException: Connection to localhost:9092 (id: 1 rack: null) failed.
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:70)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:104)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:219)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:322)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:137)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:136)
	at scala.Option.foreach(Option.scala:437)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:136)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:119)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2022-02-28 19:59:47,485] INFO Opening socket connection to server localhost/127.0.0.1:2181. (org.apache.zookeeper.ClientCnxn)
[2022-02-28 19:59:47,485] INFO SASL config status: Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2022-02-28 19:59:49,533] WARN Session 0x300b5f942b40009 for sever localhost/127.0.0.1:2181, Closing socket connection. Attempting reconnect except it is a SessionExpiredException. (org.apache.zookeeper.ClientCnxn)
java.net.ConnectException: Connection refused: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:344)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1290)
[2022-02-28 19:59:49,642] INFO [ReplicaFetcher replicaId=2, leaderId=1, fetcherId=0] Node 1 disconnected. (org.apache.kafka.clients.NetworkClient)
[2022-02-28 19:59:49,642] WARN [ReplicaFetcher replicaId=2, leaderId=1, fetcherId=0] Connection to node 1 (localhost/127.0.0.1:9092) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)
[2022-02-28 19:59:49,642] INFO [ReplicaFetcher replicaId=2, leaderId=1, fetcherId=0] Client requested connection close from node 1 (org.apache.kafka.clients.NetworkClient)
[2022-02-28 19:59:49,642] INFO [ReplicaFetcher replicaId=2, leaderId=1, fetcherId=0] Error sending fetch request (sessionId=1143473828, epoch=INITIAL) to node 1: (org.apache.kafka.clients.FetchSessionHandler)
java.io.IOException: Connection to localhost:9092 (id: 1 rack: null) failed.
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:70)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:104)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:219)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:322)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:137)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:136)
	at scala.Option.foreach(Option.scala:437)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:136)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:119)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2022-02-28 19:59:49,642] WARN [ReplicaFetcher replicaId=2, leaderId=1, fetcherId=0] Error in response for fetch request (type=FetchRequest, replicaId=2, maxWait=500, minBytes=1, maxBytes=10485760, fetchData={topic02-2=PartitionData(topicId=nwnpDpO3R5CsaOttfczqkA, fetchOffset=508515, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[7], lastFetchedEpoch=Optional[4]), topic02-1=PartitionData(topicId=nwnpDpO3R5CsaOttfczqkA, fetchOffset=737273, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[6], lastFetchedEpoch=Optional[4]), topic02-0=PartitionData(topicId=nwnpDpO3R5CsaOttfczqkA, fetchOffset=754496, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[7], lastFetchedEpoch=Optional[5])}, isolationLevel=READ_UNCOMMITTED, removed=, replaced=, metadata=(sessionId=1143473828, epoch=INITIAL), rackId=) (kafka.server.ReplicaFetcherThread)
java.io.IOException: Connection to localhost:9092 (id: 1 rack: null) failed.
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:70)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:104)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:219)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:322)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:137)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:136)
	at scala.Option.foreach(Option.scala:437)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:136)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:119)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2022-02-28 19:59:51,068] INFO Opening socket connection to server localhost/127.0.0.1:2183. (org.apache.zookeeper.ClientCnxn)
[2022-02-28 19:59:51,068] INFO SASL config status: Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2022-02-28 19:59:52,694] INFO [ReplicaFetcher replicaId=2, leaderId=1, fetcherId=0] Node 1 disconnected. (org.apache.kafka.clients.NetworkClient)
[2022-02-28 19:59:52,694] WARN [ReplicaFetcher replicaId=2, leaderId=1, fetcherId=0] Connection to node 1 (localhost/127.0.0.1:9092) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)
[2022-02-28 19:59:52,694] INFO [ReplicaFetcher replicaId=2, leaderId=1, fetcherId=0] Client requested connection close from node 1 (org.apache.kafka.clients.NetworkClient)
[2022-02-28 19:59:52,694] INFO [ReplicaFetcher replicaId=2, leaderId=1, fetcherId=0] Error sending fetch request (sessionId=1143473828, epoch=INITIAL) to node 1: (org.apache.kafka.clients.FetchSessionHandler)
java.io.IOException: Connection to localhost:9092 (id: 1 rack: null) failed.
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:70)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:104)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:219)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:322)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:137)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:136)
	at scala.Option.foreach(Option.scala:437)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:136)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:119)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2022-02-28 19:59:52,694] WARN [ReplicaFetcher replicaId=2, leaderId=1, fetcherId=0] Error in response for fetch request (type=FetchRequest, replicaId=2, maxWait=500, minBytes=1, maxBytes=10485760, fetchData={topic02-2=PartitionData(topicId=nwnpDpO3R5CsaOttfczqkA, fetchOffset=508515, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[7], lastFetchedEpoch=Optional[4]), topic02-1=PartitionData(topicId=nwnpDpO3R5CsaOttfczqkA, fetchOffset=737273, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[6], lastFetchedEpoch=Optional[4]), topic02-0=PartitionData(topicId=nwnpDpO3R5CsaOttfczqkA, fetchOffset=754496, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[7], lastFetchedEpoch=Optional[5])}, isolationLevel=READ_UNCOMMITTED, removed=, replaced=, metadata=(sessionId=1143473828, epoch=INITIAL), rackId=) (kafka.server.ReplicaFetcherThread)
java.io.IOException: Connection to localhost:9092 (id: 1 rack: null) failed.
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:70)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:104)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:219)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:322)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:137)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:136)
	at scala.Option.foreach(Option.scala:437)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:136)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:119)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2022-02-28 19:59:53,116] WARN Session 0x300b5f942b40009 for sever localhost/127.0.0.1:2183, Closing socket connection. Attempting reconnect except it is a SessionExpiredException. (org.apache.zookeeper.ClientCnxn)
java.net.ConnectException: Connection refused: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:344)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1290)
[2022-02-28 19:59:53,501] INFO Opening socket connection to server localhost/127.0.0.1:2182. (org.apache.zookeeper.ClientCnxn)
[2022-02-28 19:59:53,501] INFO SASL config status: Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2022-02-28 19:59:55,533] WARN Session 0x300b5f942b40009 for sever localhost/127.0.0.1:2182, Closing socket connection. Attempting reconnect except it is a SessionExpiredException. (org.apache.zookeeper.ClientCnxn)
java.net.ConnectException: Connection refused: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:344)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1290)
[2022-02-28 19:59:55,751] INFO [ReplicaFetcher replicaId=2, leaderId=1, fetcherId=0] Node 1 disconnected. (org.apache.kafka.clients.NetworkClient)
[2022-02-28 19:59:55,752] WARN [ReplicaFetcher replicaId=2, leaderId=1, fetcherId=0] Connection to node 1 (localhost/127.0.0.1:9092) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)
[2022-02-28 19:59:55,752] INFO [ReplicaFetcher replicaId=2, leaderId=1, fetcherId=0] Client requested connection close from node 1 (org.apache.kafka.clients.NetworkClient)
[2022-02-28 19:59:55,752] INFO [ReplicaFetcher replicaId=2, leaderId=1, fetcherId=0] Error sending fetch request (sessionId=1143473828, epoch=INITIAL) to node 1: (org.apache.kafka.clients.FetchSessionHandler)
java.io.IOException: Connection to localhost:9092 (id: 1 rack: null) failed.
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:70)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:104)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:219)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:322)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:137)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:136)
	at scala.Option.foreach(Option.scala:437)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:136)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:119)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2022-02-28 19:59:55,753] WARN [ReplicaFetcher replicaId=2, leaderId=1, fetcherId=0] Error in response for fetch request (type=FetchRequest, replicaId=2, maxWait=500, minBytes=1, maxBytes=10485760, fetchData={topic02-2=PartitionData(topicId=nwnpDpO3R5CsaOttfczqkA, fetchOffset=508515, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[7], lastFetchedEpoch=Optional[4]), topic02-1=PartitionData(topicId=nwnpDpO3R5CsaOttfczqkA, fetchOffset=737273, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[6], lastFetchedEpoch=Optional[4]), topic02-0=PartitionData(topicId=nwnpDpO3R5CsaOttfczqkA, fetchOffset=754496, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[7], lastFetchedEpoch=Optional[5])}, isolationLevel=READ_UNCOMMITTED, removed=, replaced=, metadata=(sessionId=1143473828, epoch=INITIAL), rackId=) (kafka.server.ReplicaFetcherThread)
java.io.IOException: Connection to localhost:9092 (id: 1 rack: null) failed.
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:70)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:104)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:219)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:322)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:137)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:136)
	at scala.Option.foreach(Option.scala:437)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:136)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:119)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2022-02-28 19:59:55,869] INFO Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2181. (org.apache.zookeeper.ClientCnxn)
[2022-02-28 19:59:55,869] INFO SASL config status: Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2022-02-28 19:59:57,886] WARN Session 0x300b5f942b40009 for sever localhost/0:0:0:0:0:0:0:1:2181, Closing socket connection. Attempting reconnect except it is a SessionExpiredException. (org.apache.zookeeper.ClientCnxn)
java.net.ConnectException: Connection refused: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:344)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1290)
[2022-02-28 19:59:58,777] INFO [ReplicaFetcher replicaId=2, leaderId=1, fetcherId=0] Node 1 disconnected. (org.apache.kafka.clients.NetworkClient)
[2022-02-28 19:59:58,777] WARN [ReplicaFetcher replicaId=2, leaderId=1, fetcherId=0] Connection to node 1 (localhost/127.0.0.1:9092) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)
[2022-02-28 19:59:58,777] INFO [ReplicaFetcher replicaId=2, leaderId=1, fetcherId=0] Client requested connection close from node 1 (org.apache.kafka.clients.NetworkClient)
[2022-02-28 19:59:58,777] INFO [ReplicaFetcher replicaId=2, leaderId=1, fetcherId=0] Error sending fetch request (sessionId=1143473828, epoch=INITIAL) to node 1: (org.apache.kafka.clients.FetchSessionHandler)
java.io.IOException: Connection to localhost:9092 (id: 1 rack: null) failed.
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:70)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:104)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:219)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:322)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:137)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:136)
	at scala.Option.foreach(Option.scala:437)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:136)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:119)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2022-02-28 19:59:58,777] WARN [ReplicaFetcher replicaId=2, leaderId=1, fetcherId=0] Error in response for fetch request (type=FetchRequest, replicaId=2, maxWait=500, minBytes=1, maxBytes=10485760, fetchData={topic02-2=PartitionData(topicId=nwnpDpO3R5CsaOttfczqkA, fetchOffset=508515, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[7], lastFetchedEpoch=Optional[4]), topic02-1=PartitionData(topicId=nwnpDpO3R5CsaOttfczqkA, fetchOffset=737273, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[6], lastFetchedEpoch=Optional[4]), topic02-0=PartitionData(topicId=nwnpDpO3R5CsaOttfczqkA, fetchOffset=754496, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[7], lastFetchedEpoch=Optional[5])}, isolationLevel=READ_UNCOMMITTED, removed=, replaced=, metadata=(sessionId=1143473828, epoch=INITIAL), rackId=) (kafka.server.ReplicaFetcherThread)
java.io.IOException: Connection to localhost:9092 (id: 1 rack: null) failed.
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:70)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:104)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:219)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:322)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:137)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:136)
	at scala.Option.foreach(Option.scala:437)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:136)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:119)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2022-02-28 19:59:59,951] INFO Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2183. (org.apache.zookeeper.ClientCnxn)
[2022-02-28 19:59:59,951] INFO SASL config status: Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
