[2022-02-28 14:19:19,947] INFO [GroupCoordinator 2]: Member console-consumer-cdfa1b43-afef-4201-8a22-59d109c687c0 in group console-consumer-69689 has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2022-02-28 14:19:20,361] INFO [ReplicaFetcher replicaId=2, leaderId=1, fetcherId=0] Node 1 disconnected. (org.apache.kafka.clients.NetworkClient)
[2022-02-28 14:19:22,607] WARN Client session timed out, have not heard from server in 974818ms for session id 0x300b5f942b40008 (org.apache.zookeeper.ClientCnxn)
[2022-02-28 14:19:22,566] INFO [GroupCoordinator 2]: Preparing to rebalance group console-consumer-69689 in state PreparingRebalance with old generation 1 (__consumer_offsets-9) (reason: removing member console-consumer-cdfa1b43-afef-4201-8a22-59d109c687c0 on heartbeat expiration) (kafka.coordinator.group.GroupCoordinator)
[2022-02-28 14:19:26,511] WARN Session 0x300b5f942b40008 for sever localhost/127.0.0.1:2183, Closing socket connection. Attempting reconnect except it is a SessionExpiredException. (org.apache.zookeeper.ClientCnxn)
org.apache.zookeeper.ClientCnxn$SessionTimeoutException: Client session timed out, have not heard from server in 974818ms for session id 0x300b5f942b40008
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1258)
[2022-02-28 14:19:26,582] INFO [ReplicaFetcher replicaId=2, leaderId=1, fetcherId=0] Cancelled in-flight FETCH request with correlation id 109677 due to node 1 being disconnected (elapsed time since creation: 971535ms, elapsed time since send: 971535ms, request timeout: 30000ms) (org.apache.kafka.clients.NetworkClient)
[2022-02-28 14:19:26,582] INFO [GroupCoordinator 2]: Group console-consumer-69689 with generation 2 is now empty (__consumer_offsets-9) (kafka.coordinator.group.GroupCoordinator)
[2022-02-28 14:19:26,966] INFO [ReplicaFetcher replicaId=2, leaderId=1, fetcherId=0] Client requested connection close from node 1 (org.apache.kafka.clients.NetworkClient)
[2022-02-28 14:19:27,148] INFO [ReplicaFetcher replicaId=2, leaderId=1, fetcherId=0] Error sending fetch request (sessionId=50951882, epoch=25047) to node 1: (org.apache.kafka.clients.FetchSessionHandler)
java.io.IOException: Connection to 1 was disconnected before the response was read
	at org.apache.kafka.clients.NetworkClientUtils.sendAndReceive(NetworkClientUtils.java:99)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:109)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:219)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:322)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:137)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:136)
	at scala.Option.foreach(Option.scala:437)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:136)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:119)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2022-02-28 14:19:28,472] WARN [ReplicaFetcher replicaId=2, leaderId=1, fetcherId=0] Error in response for fetch request (type=FetchRequest, replicaId=2, maxWait=500, minBytes=1, maxBytes=10485760, fetchData={}, isolationLevel=READ_UNCOMMITTED, removed=, replaced=, metadata=(sessionId=50951882, epoch=25047), rackId=) (kafka.server.ReplicaFetcherThread)
java.io.IOException: Connection to 1 was disconnected before the response was read
	at org.apache.kafka.clients.NetworkClientUtils.sendAndReceive(NetworkClientUtils.java:99)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:109)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:219)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:322)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:137)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:136)
	at scala.Option.foreach(Option.scala:437)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:136)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:119)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2022-02-28 14:19:29,574] INFO Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2181. (org.apache.zookeeper.ClientCnxn)
[2022-02-28 14:19:29,598] INFO SASL config status: Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2022-02-28 14:19:29,701] INFO Socket connection established, initiating session, client: /0:0:0:0:0:0:0:1:51596, server: localhost/0:0:0:0:0:0:0:1:2181 (org.apache.zookeeper.ClientCnxn)
[2022-02-28 14:19:30,370] WARN Unable to reconnect to ZooKeeper service, session 0x300b5f942b40008 has expired (org.apache.zookeeper.ClientCnxn)
[2022-02-28 14:19:30,372] WARN Session 0x300b5f942b40008 for sever localhost/0:0:0:0:0:0:0:1:2181, Closing socket connection. Attempting reconnect except it is a SessionExpiredException. (org.apache.zookeeper.ClientCnxn)
org.apache.zookeeper.ClientCnxn$SessionExpiredException: Unable to reconnect to ZooKeeper service, session 0x300b5f942b40008 has expired
	at org.apache.zookeeper.ClientCnxn$SendThread.onConnected(ClientCnxn.java:1434)
	at org.apache.zookeeper.ClientCnxnSocket.readConnectResult(ClientCnxnSocket.java:154)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doIO(ClientCnxnSocketNIO.java:86)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:350)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1290)
[2022-02-28 14:19:30,378] INFO EventThread shut down for session: 0x300b5f942b40008 (org.apache.zookeeper.ClientCnxn)
[2022-02-28 14:19:30,387] INFO [ZooKeeperClient Kafka server] Session expired. (kafka.zookeeper.ZooKeeperClient)
[2022-02-28 14:19:30,527] INFO [ZooKeeperClient Kafka server] Initializing a new session to localhost:2181,localhost:2182,localhost:2183. (kafka.zookeeper.ZooKeeperClient)
[2022-02-28 14:19:30,536] INFO Initiating client connection, connectString=localhost:2181,localhost:2182,localhost:2183 sessionTimeout=18000 watcher=kafka.zookeeper.ZooKeeperClient$ZooKeeperClientWatcher$@7c7b252e (org.apache.zookeeper.ZooKeeper)
[2022-02-28 14:19:30,586] INFO [GroupCoordinator 2]: Dynamic member with unknown member id joins group console-consumer-69689 in Empty state. Created a new member id console-consumer-039088b7-4622-4e52-9862-e7ba6f73ecde and request the member to rejoin with this id. (kafka.coordinator.group.GroupCoordinator)
[2022-02-28 14:19:30,615] INFO jute.maxbuffer value is 4194304 Bytes (org.apache.zookeeper.ClientCnxnSocket)
[2022-02-28 14:19:30,643] INFO zookeeper.request.timeout value is 0. feature enabled=false (org.apache.zookeeper.ClientCnxn)
[2022-02-28 14:19:30,669] INFO Opening socket connection to server localhost/127.0.0.1:2182. (org.apache.zookeeper.ClientCnxn)
[2022-02-28 14:19:30,670] INFO SASL config status: Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2022-02-28 14:19:30,673] INFO Socket connection established, initiating session, client: /127.0.0.1:51609, server: localhost/127.0.0.1:2182 (org.apache.zookeeper.ClientCnxn)
[2022-02-28 14:19:30,681] INFO [GroupCoordinator 2]: Preparing to rebalance group console-consumer-69689 in state PreparingRebalance with old generation 2 (__consumer_offsets-9) (reason: Adding new member console-consumer-039088b7-4622-4e52-9862-e7ba6f73ecde with group instance id None) (kafka.coordinator.group.GroupCoordinator)
[2022-02-28 14:19:30,713] INFO [GroupCoordinator 2]: Stabilized group console-consumer-69689 generation 3 (__consumer_offsets-9) with 1 members (kafka.coordinator.group.GroupCoordinator)
[2022-02-28 14:19:30,820] INFO [GroupCoordinator 2]: Assignment received from leader console-consumer-039088b7-4622-4e52-9862-e7ba6f73ecde for group console-consumer-69689 for generation 3. The group has 1 members, 0 of which are static. (kafka.coordinator.group.GroupCoordinator)
[2022-02-28 14:19:30,919] INFO Session establishment complete on server localhost/127.0.0.1:2182, session id = 0x200b5f9003c0008, negotiated timeout = 18000 (org.apache.zookeeper.ClientCnxn)
[2022-02-28 14:19:31,253] INFO Creating /brokers/ids/2 (is it secure? false) (kafka.zk.KafkaZkClient)
[2022-02-28 14:19:31,285] INFO Updated cache from existing FinalizedFeaturesAndEpoch(features=Features{}, epoch=0) to latest FinalizedFeaturesAndEpoch(features=Features{}, epoch=0). (kafka.server.FinalizedFeatureCache)
[2022-02-28 14:19:31,314] INFO Stat of the created znode at /brokers/ids/2 is: 4294967721,4294967721,1646038171289,1646038171289,1,0,0,144315269131272200,202,0,4294967721
 (kafka.zk.KafkaZkClient)
[2022-02-28 14:19:31,317] INFO Registered broker 2 at path /brokers/ids/2 with addresses: PLAINTEXT://localhost:9093, czxid (broker epoch): 4294967721 (kafka.zk.KafkaZkClient)
